site_name: Neha Rajganesh
site_url: https://neharajganesh.github.io/PersonalBlog/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top

  palette:
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Hey I'm Neha!: about/about.md
  - Blog: blog/index.md
  - LinkedIn: linkedin.md

plugins:
  - search
  #- blog

extra_css:
  - styles/extra.css